package modbus

var (
	auchCRCHi = []byte{
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41,
		0x00, 0xC1, 0x81, 0x40, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0,
		0x80, 0x41, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1, 0x81, 0x40,
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1,
		0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0, 0x80, 0x41,
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1,
		0x81, 0x40, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41,
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x00, 0xC1, 0x81, 0x40,
		0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1,
		0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1, 0x81, 0x40,
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x00, 0xC1, 0x81, 0x40,
		0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0,
		0x80, 0x41, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1, 0x81, 0x40,
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41,
		0x00, 0xC1, 0x81, 0x40, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41,
		0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40, 0x00, 0xC1, 0x81, 0x40,
		0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0, 0x80, 0x41, 0x00, 0xC1,
		0x81, 0x40, 0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41,
		0x00, 0xC1, 0x81, 0x40, 0x01, 0xC0, 0x80, 0x41, 0x01, 0xC0,
		0x80, 0x41, 0x00, 0xC1, 0x81, 0x40,
	}
	auchCRCLo = []byte{
		0x00, 0xC0, 0xC1, 0x01, 0xC3, 0x03, 0x02, 0xC2, 0xC6, 0x06,
		0x07, 0xC7, 0x05, 0xC5, 0xC4, 0x04, 0xCC, 0x0C, 0x0D, 0xCD,
		0x0F, 0xCF, 0xCE, 0x0E, 0x0A, 0xCA, 0xCB, 0x0B, 0xC9, 0x09,
		0x08, 0xC8, 0xD8, 0x18, 0x19, 0xD9, 0x1B, 0xDB, 0xDA, 0x1A,
		0x1E, 0xDE, 0xDF, 0x1F, 0xDD, 0x1D, 0x1C, 0xDC, 0x14, 0xD4,
		0xD5, 0x15, 0xD7, 0x17, 0x16, 0xD6, 0xD2, 0x12, 0x13, 0xD3,
		0x11, 0xD1, 0xD0, 0x10, 0xF0, 0x30, 0x31, 0xF1, 0x33, 0xF3,
		0xF2, 0x32, 0x36, 0xF6, 0xF7, 0x37, 0xF5, 0x35, 0x34, 0xF4,
		0x3C, 0xFC, 0xFD, 0x3D, 0xFF, 0x3F, 0x3E, 0xFE, 0xFA, 0x3A,
		0x3B, 0xFB, 0x39, 0xF9, 0xF8, 0x38, 0x28, 0xE8, 0xE9, 0x29,
		0xEB, 0x2B, 0x2A, 0xEA, 0xEE, 0x2E, 0x2F, 0xEF, 0x2D, 0xED,
		0xEC, 0x2C, 0xE4, 0x24, 0x25, 0xE5, 0x27, 0xE7, 0xE6, 0x26,
		0x22, 0xE2, 0xE3, 0x23, 0xE1, 0x21, 0x20, 0xE0, 0xA0, 0x60,
		0x61, 0xA1, 0x63, 0xA3, 0xA2, 0x62, 0x66, 0xA6, 0xA7, 0x67,
		0xA5, 0x65, 0x64, 0xA4, 0x6C, 0xAC, 0xAD, 0x6D, 0xAF, 0x6F,
		0x6E, 0xAE, 0xAA, 0x6A, 0x6B, 0xAB, 0x69, 0xA9, 0xA8, 0x68,
		0x78, 0xB8, 0xB9, 0x79, 0xBB, 0x7B, 0x7A, 0xBA, 0xBE, 0x7E,
		0x7F, 0xBF, 0x7D, 0xBD, 0xBC, 0x7C, 0xB4, 0x74, 0x75, 0xB5,
		0x77, 0xB7, 0xB6, 0x76, 0x72, 0xB2, 0xB3, 0x73, 0xB1, 0x71,
		0x70, 0xB0, 0x50, 0x90, 0x91, 0x51, 0x93, 0x53, 0x52, 0x92,
		0x96, 0x56, 0x57, 0x97, 0x55, 0x95, 0x94, 0x54, 0x9C, 0x5C,
		0x5D, 0x9D, 0x5F, 0x9F, 0x9E, 0x5E, 0x5A, 0x9A, 0x9B, 0x5B,
		0x99, 0x59, 0x58, 0x98, 0x88, 0x48, 0x49, 0x89, 0x4B, 0x8B,
		0x8A, 0x4A, 0x4E, 0x8E, 0x8F, 0x4F, 0x8D, 0x4D, 0x4C, 0x8C,
		0x44, 0x84, 0x85, 0x45, 0x87, 0x47, 0x46, 0x86, 0x82, 0x42,
		0x43, 0x83, 0x41, 0x81, 0x80, 0x40,
	}
)

//寄存器表号
const (
	REGISTER_TABLE_ONE uint8 = 1
	REGISTER_TABLE_TWO uint8 = 2
)

//modbus功能码
const (
	WRITESINGLE_SUCCESS         uint16 = 0x06
	WRITESINGLE_FAILED          uint16 = 0x06 | (1 << 7)
	WRITERANGE_SUCCESS          uint16 = 0x10
	WRITERANGE_FAILED           uint16 = 0x10 | (1 << 7)
	READRANGE_SUCCESS           uint16 = 0x03
	READRANGE_FAILED            uint16 = 0x03 | (1 << 7)
	SNAPSHOOT_READRANGE_SUCCESS uint16 = 0x64
	SNAPSHOOT_READRANGE_FAILED  uint16 = 0x64 | (1 << 7)
)

//modbus响应错误码
const (
	ERRORCODE_ADDRERROR     uint8 = 0x01
	ERRORCODE_REGISTERERROR uint8 = 0x02
	ERRORCODE_DEVICEOFFLINE uint8 = 0x03
)

//消息类型
const (
	MSGTYPE_TIMEDUPLOAD               uint8 = 0xb1
	MSGTYPE_UPLOADVALUES              uint8 = 0xb3
	MSGTYPE_CMD                       uint8 = 0xb5
	MSGTYPE_CMDRESULT                 uint8 = 0xb6
	MSGTYPE_RUNTIME                   uint8 = 0xb7
	MSGTYPE_RUNTIME_RESULT            uint8 = 0xb8
	MSGTYPE_SETTING                   uint8 = 0xb9
	MSGTYPE_SETTING_RESULT            uint8 = 0xba
	MSGTYPE_ERROR                     uint8 = 0xc1
	MSGTYPE_ALARM                     uint8 = 0xc3
	MSGTYPE_HARDWAREFAULT             uint8 = 0xc5
	MSGTYPE_SWITCHSTATE               uint8 = 0xc7
	MSGTYPE_SWITCHMODE                uint8 = 0xc9
	MSGTYPE_ELECTRICLEAKAGETESTUPLOAD uint8 = 0xcb
	MSGTYPE_EQ_CHANGE                 uint8 = 0xcd
	MSGTYPE_HOSTDETAIL                uint8 = 0xd1
	MSGTYPE_ICCID                     uint8 = 0xd3
	MSGTYPE_ICCID_RESULT              uint8 = 0xd4
	MSGTYPE_ALLSWITCH                 uint8 = 0xd5
	MSGTYPE_ALLSWITCH_RESULT          uint8 = 0xd6
	MSGTYPE_SNAPSHOOT_TIMEDUPLOAD     uint8 = 0xd7
	MSGTYPE_ALLSTATE                  uint8 = 0xd9
	MSGTYPE_ALLSTATE_RESULT           uint8 = 0xda
	MSGTYPE_GETSNAPSHOOT              uint8 = 0xdb
	MSGTYPE_GETSNAPSHOOT_RESULT       uint8 = 0xdc
	MSGTYPE_TIMESTAMP                 uint8 = 0x90
	MSGTYPE_TIMESTAMP_RESULT          uint8 = 0x91
)

//设备类型
const (
	DEVICEREGISTER_TYPE_ONESWITCH                                              uint8 = 0
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ELECTRICLEAKAGEPROTECTION                uint8 = 1
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ARCDETECTION                             uint8 = 2
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION   uint8 = 3
	DEVICEREGISTER_TYPE_TWOSWITCH                                              uint8 = 4
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ELECTRICLEAKAGEPROTECTION                uint8 = 5
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ARCDETECTION                             uint8 = 6
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION   uint8 = 7
	DEVICEREGISTER_TYPE_THREESWITCH                                            uint8 = 8
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ELECTRICLEAKAGEPROTECTION              uint8 = 9
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ARCDETECTION                           uint8 = 10
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION uint8 = 11
	DEVICEREGISTER_TYPE_FOURSWITCH                                             uint8 = 12
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ELECTRICLEAKAGEPROTECTION               uint8 = 13
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ARCDETECTION                            uint8 = 14
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION  uint8 = 15
)

//设备寄存器1
const (
	DEVICEREGISTER_ONE_CMD                   uint16 = 0
	DEVICEREGISTER_ONE_HARDWAREFAULT         uint16 = 3
	DEVICEREGISTER_ONE_ALARMSTATE            uint16 = 4
	DEVICEREGISTER_ONE_ERRORSTATE            uint16 = 6
	DEVICEREGISTER_ONE_SWITCHSTATE           uint16 = 8
	DEVICEREGISTER_ONE_SWITCHMODE            uint16 = 9
	DEVICEREGISTER_ONE_RMS_U                 uint16 = 10
	DEVICEREGISTER_ONE_RMS_I                 uint16 = 11
	DEVICEREGISTER_ONE_POWER_P               uint16 = 13
	DEVICEREGISTER_ONE_POWER_Q               uint16 = 15
	DEVICEREGISTER_ONE_ENERGY_PT             uint16 = 17
	DEVICEREGISTER_ONE_ENERGY_PT_L           uint16 = 19
	DEVICEREGISTER_ONE_POWER_F               uint16 = 21
	DEVICEREGISTER_ONE_FREQ                  uint16 = 22
	DEVICEREGISTER_ONE_RMS_IL                uint16 = 23
	DEVICEREGISTER_ONE_TEMPERATURE           uint16 = 24
	DEVICEREGISTER_ONE_MOTOR_RUNTIMES        uint16 = 25
	DEVICEREGISTER_ONE_ERRORTIMES            uint16 = 26
	DEVICEREGISTER_ONE_ALARMENABLE           uint16 = 27
	DEVICEREGISTER_ONE_ERRORENABLE           uint16 = 28
	DEVICEREGISTER_ONE_VOLTAGELIMITRSTENABLE uint16 = 29
	DEVICEREGISTER_ONE_IH_P                  uint16 = 30
	DEVICEREGISTER_ONE_IH                    uint16 = 31
	DEVICEREGISTER_ONE_UH_P                  uint16 = 32
	DEVICEREGISTER_ONE_UH                    uint16 = 33
	DEVICEREGISTER_ONE_UL_P                  uint16 = 34
	DEVICEREGISTER_ONE_UL                    uint16 = 35
	DEVICEREGISTER_ONE_PH_P                  uint16 = 36
	DEVICEREGISTER_ONE_PH                    uint16 = 37
	DEVICEREGISTER_ONE_EH_P                  uint16 = 38
	DEVICEREGISTER_ONE_EH                    uint16 = 40
	DEVICEREGISTER_ONE_IL_P                  uint16 = 42
	DEVICEREGISTER_ONE_IL                    uint16 = 43
	DEVICEREGISTER_ONE_TH_P                  uint16 = 44
	DEVICEREGISTER_ONE_TH                    uint16 = 45
	DEVICEREGISTER_ONE_UHL_CT                uint16 = 46
	DEVICEREGISTER_ONE_UHL_RT                uint16 = 47
	DEVICEREGISTER_ONE_IH_PH_CT              uint16 = 48
	DEVICEREGISTER_ONE_STTIMER_0             uint16 = 49
	DEVICEREGISTER_ONE_STTIMER_1             uint16 = 57
	DEVICEREGISTER_ONE_STTIMER_2             uint16 = 65
	DEVICEREGISTER_ONE_STTIMER_3             uint16 = 73
)

//设备寄存器2
const (
	DEVICEREGISTER_TWO_CMD                   uint16 = 0
	DEVICEREGISTER_TWO_HARDWAREFAULT         uint16 = 3
	DEVICEREGISTER_TWO_ALARMSTATE            uint16 = 4
	DEVICEREGISTER_TWO_ERRORSTATE            uint16 = 6
	DEVICEREGISTER_TWO_SWITCHSTATE           uint16 = 8
	DEVICEREGISTER_TWO_SWITCHMODE            uint16 = 9
	DEVICEREGISTER_TWO_RMS_U                 uint16 = 10
	DEVICEREGISTER_TWO_RMS_I                 uint16 = 11
	DEVICEREGISTER_TWO_POWER_P               uint16 = 13
	DEVICEREGISTER_TWO_POWER_Q               uint16 = 15
	DEVICEREGISTER_TWO_ENERGY_PT             uint16 = 17
	DEVICEREGISTER_TWO_ENERGY_PT_L           uint16 = 19
	DEVICEREGISTER_TWO_POWER_F               uint16 = 21
	DEVICEREGISTER_TWO_FREQ                  uint16 = 22
	DEVICEREGISTER_TWO_RMS_IL                uint16 = 23
	DEVICEREGISTER_TWO_TEMPERATURE           uint16 = 24
	DEVICEREGISTER_TWO_MOTOR_RUNTIMES        uint16 = 25
	DEVICEREGISTER_TWO_ERRORTIMES            uint16 = 26
	DEVICEREGISTER_TWO_ALARMENABLE           uint16 = 27
	DEVICEREGISTER_TWO_ERRORENABLE           uint16 = 28
	DEVICEREGISTER_TWO_VOLTAGELIMITRSTENABLE uint16 = 29
	DEVICEREGISTER_TWO_IH_P                  uint16 = 30
	DEVICEREGISTER_TWO_IH                    uint16 = 31
	DEVICEREGISTER_TWO_UH_P                  uint16 = 32
	DEVICEREGISTER_TWO_UH                    uint16 = 33
	DEVICEREGISTER_TWO_UL_P                  uint16 = 34
	DEVICEREGISTER_TWO_UL                    uint16 = 35
	DEVICEREGISTER_TWO_PH_P                  uint16 = 36
	DEVICEREGISTER_TWO_PH                    uint16 = 37
	DEVICEREGISTER_TWO_EH_P                  uint16 = 38
	DEVICEREGISTER_TWO_EH                    uint16 = 40
	DEVICEREGISTER_TWO_IL_P                  uint16 = 42
	DEVICEREGISTER_TWO_IL                    uint16 = 43
	DEVICEREGISTER_TWO_TH_P                  uint16 = 44
	DEVICEREGISTER_TWO_TH                    uint16 = 45
	DEVICEREGISTER_TWO_UHL_CT                uint16 = 46
	DEVICEREGISTER_TWO_UHL_RT                uint16 = 47
	DEVICEREGISTER_TWO_IH_PH_CT              uint16 = 48
	DEVICEREGISTER_TWO_STTIMER_0             uint16 = 49
	DEVICEREGISTER_TWO_STTIMER_1             uint16 = 57
	DEVICEREGISTER_TWO_STTIMER_2             uint16 = 65
	DEVICEREGISTER_TWO_STTIMER_3             uint16 = 73
)

//设备寄存器1常量数据
const (
	//硬件故障
	DEVICEREGISTER_ONE_HARDWAREFAULT_MEASUREFAULT    uint8 = 0
	DEVICEREGISTER_ONE_HARDWAREFAULT_ELECTRICLEAKAGE uint8 = 1
	DEVICEREGISTER_ONE_HARDWAREFAULT_TRANSMITTFAULT  uint8 = 2
	DEVICEREGISTER_ONE_HARDWAREFAULT_OPENSTATELIMIT  uint8 = 3
	DEVICEREGISTER_ONE_HARDWAREFAULT_OPENSTOPLIMIT   uint8 = 4
	DEVICEREGISTER_ONE_HARDWAREFAULT_CLOSESTATELIMIT uint8 = 5
	DEVICEREGISTER_ONE_HARDWAREFAULT_CLOSESTOPLIMIT  uint8 = 6
	//预警状态
	DEVICEREGISTER_ONE_ALARMSTATE_OVERFLOW         uint8 = 0
	DEVICEREGISTER_ONE_ALARMSTATE_OVERVOLTAGE      uint8 = 1
	DEVICEREGISTER_ONE_ALARMSTATE_UNDERVOLTAGE     uint8 = 2
	DEVICEREGISTER_ONE_ALARMSTATE_OVERDRIVE        uint8 = 4
	DEVICEREGISTER_ONE_ALARMSTATE_ELECTRICQUANTITY uint8 = 5
	DEVICEREGISTER_ONE_ALARMSTATE_OVERHEAT         uint8 = 6
	//故障状态
	DEVICEREGISTER_ONE_ERRORSTATE_OVERFLOW         uint8 = 0
	DEVICEREGISTER_ONE_ERRORSTATE_OVERVOLTAGE      uint8 = 1
	DEVICEREGISTER_ONE_ERRORSTATE_UNDERVOLTAGE     uint8 = 2
	DEVICEREGISTER_ONE_ERRORSTATE_OVERDRIVE        uint8 = 4
	DEVICEREGISTER_ONE_ERRORSTATE_ELECTRICQUANTITY uint8 = 5
	DEVICEREGISTER_ONE_ERRORSTATE_OVERHEAT         uint8 = 6
	DEVICEREGISTER_ONE_ERRORSTATE_SHORTOUT         uint8 = 8
	DEVICEREGISTER_ONE_ERRORSTATE_ELECTRICLEAKAGE  uint8 = 9
	DEVICEREGISTER_ONE_ERRORSTATE_GROUNDLEAD       uint8 = 10
	DEVICEREGISTER_ONE_ERRORSTATE_ELECTRICARC      uint8 = 11
	//开关状态
	DEVICEREGISTER_ONE_SWITCHSTATE_CLOSE                    uint16 = 0
	DEVICEREGISTER_ONE_SWITCHSTATE_OPEN                     uint16 = 1
	DEVICEREGISTER_ONE_SWITCHSTATE_BUTTONCLOSE              uint16 = 2
	DEVICEREGISTER_ONE_SWITCHSTATE_BUTTONOPEN               uint16 = 3
	DEVICEREGISTER_ONE_SWITCHSTATE_REMOTECLOSE              uint16 = 4
	DEVICEREGISTER_ONE_SWITCHSTATE_REMOTEOPEN               uint16 = 5
	DEVICEREGISTER_ONE_SWITCHSTATE_FAULTCLOSE               uint16 = 6
	DEVICEREGISTER_ONE_SWITCHSTATE_AFTERFAULTAUTOOPEN       uint16 = 7
	DEVICEREGISTER_ONE_SWITCHSTATE_TIMEDCLOSE               uint16 = 8
	DEVICEREGISTER_ONE_SWITCHSTATE_TIMEDOPEN                uint16 = 9
	DEVICEREGISTER_ONE_SWITCHSTATE_SHORTOUTCLOSE            uint16 = 10
	DEVICEREGISTER_ONE_SWITCHSTATE_ELECTRICLEAKAGECLOSE     uint16 = 11
	DEVICEREGISTER_ONE_SWITCHSTATE_ELECTRICLEAKAGETESTCLOSE uint16 = 12
	//开关模式
	DEVICEREGISTER_ONE_SWITCHMODE_NORMAL     uint16 = 0
	DEVICEREGISTER_ONE_SWITCHMODE_LOCALLOCK  uint16 = 1
	DEVICEREGISTER_ONE_SWITCHMODE_REMOTELOCK uint16 = 2
	DEVICEREGISTER_ONE_SWITCHMODE_FAULTLOCK  uint16 = 4
	DEVICEREGISTER_ONE_SWITCHMODE_OFFLINE    uint16 = 8
	//预警启用
	DEVICEREGISTER_ONE_ALARMENABLE_OVERFLOW         uint8 = 0
	DEVICEREGISTER_ONE_ALARMENABLE_OVERVOLTAGE      uint8 = 1
	DEVICEREGISTER_ONE_ALARMENABLE_UNDERVOLTAGE     uint8 = 2
	DEVICEREGISTER_ONE_ALARMENABLE_OVERDRIVE        uint8 = 4
	DEVICEREGISTER_ONE_ALARMENABLE_ELECTRICQUANTITY uint8 = 5
	DEVICEREGISTER_ONE_ALARMENABLE_OVERHEAT         uint8 = 6
	//故障保护启用
	DEVICEREGISTER_ONE_ERRORENABLE_OVERFLOW         uint8 = 0
	DEVICEREGISTER_ONE_ERRORENABLE_OVERVOLTAGE      uint8 = 1
	DEVICEREGISTER_ONE_ERRORENABLE_UNDERVOLTAGE     uint8 = 2
	DEVICEREGISTER_ONE_ERRORENABLE_OVERDRIVE        uint8 = 4
	DEVICEREGISTER_ONE_ERRORENABLE_ELECTRICQUANTITY uint8 = 5
	DEVICEREGISTER_ONE_ERRORENABLE_OVERHEAT         uint8 = 6
	DEVICEREGISTER_ONE_ERRORENABLE_SHORTOUT         uint8 = 8
	DEVICEREGISTER_ONE_ERRORENABLE_ELECTRICARC      uint8 = 11
	//过欠压恢复启用
	DEVICEREGISTER_ONE_VOLTAGELIMITRSTENABLE_CLOSE uint16 = 0
	DEVICEREGISTER_ONE_VOLTAGELIMITRSTENABLE_OPEN  uint16 = 1
	//下发命令
	DEVICEREGISTER_ONE_CMD_REMOTEOPEN          uint16 = 0x03
	DEVICEREGISTER_ONE_CMD_REMOTECLOSE         uint16 = 0x04
	DEVICEREGISTER_ONE_CMD_REMOTELOCK          uint16 = 0x05
	DEVICEREGISTER_ONE_CMD_REMOTEUNLOCK        uint16 = 0x06
	DEVICEREGISTER_ONE_CMD_ELECTRICLEAKAGETEST uint16 = 0x07
	DEVICEREGISTER_ONE_CMD_CLEARFAULT          uint16 = 0x08
	DEVICEREGISTER_ONE_CMD_RESET               uint16 = 0x09
	//定时功能——任务类型
	DEVICEREGISTER_ONE_STTIMER_TYPE_CLOSE               uint8 = 0
	DEVICEREGISTER_ONE_STTIMER_TYPE_OPEN                uint8 = 1
	DEVICEREGISTER_ONE_STTIMER_TYPE_ELECTRICLEAKAGETEST uint8 = 2
	//定时任务——周期类型
	DEVICEREGISTER_ONE_STTIMER_CIRCLE_ONCE    uint8 = 0
	DEVICEREGISTER_ONE_STTIMER_CIRCLE_DAILY   uint8 = 1
	DEVICEREGISTER_ONE_STTIMER_CIRCLE_WEEKLY  uint8 = 2
	DEVICEREGISTER_ONE_STTIMER_CIRCLE_MONTHLY uint8 = 3
	//定时任务——状态
	DEVICEREGISTER_ONE_STTIMER_STATE_CLOSE             uint8 = 0
	DEVICEREGISTER_ONE_STTIMER_STATE_OPEN              uint8 = 1
	DEVICEREGISTER_ONE_STTIMER_STATE_NOTEXECUTE        uint8 = 2
	DEVICEREGISTER_ONE_STTIMER_STATE_EXECUTED          uint8 = 3
	DEVICEREGISTER_ONE_STTIMER_STATE_EXECUTEDCONTINUED uint8 = 4
)

//主机寄存器
const (
	HOSTREGISTER_ISSUEDCMD       uint16 = 0
	HOSTREGISTER_VERSION         uint16 = 6
	HOSTREGISTER_SIGNALINTENSITY uint16 = 7
	HOSTREGISTER_INTERNETMODE    uint16 = 8
	HOSTREGISTER_DEVICESCOUNT    uint16 = 9
	HOSTREGISTER_UPLOADINTERVAL  uint16 = 10
)

//主机寄存器数据
const (
	//下发命令
	HOSTREGISTER_ISSUEDCMD_INIT       uint16 = 1
	HOSTREGISTER_ISSUEDCMD_CHANGE     uint16 = 2
	HOSTREGISTER_ISSUEDCMD_CHANGEADDR uint16 = 5
	//通讯方式
	HOSTREGISTER_INTERNETMODE_ETHERNET uint16 = 1
	HOSTREGISTER_INTERNETMODE_WIFI     uint16 = 2
	HOSTREGISTER_INTERNETMODE_4G       uint16 = 3
	HOSTREGISTER_INTERNETMODE_485      uint16 = 4
)

//协议变量，基地址、大小端
const (
	BIGEND          bool   = false
	CRC_BIGEND      bool   = false
	DEVICE_BASEADDR uint16 = 0
	HOST_BASEADDR   uint16 = 0
)

var DEVICETYPE_MSG = map[uint8]string{
	DEVICEREGISTER_TYPE_ONESWITCH:                                              "1分路",
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ELECTRICLEAKAGEPROTECTION:                "1分路带漏电保护",
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ARCDETECTION:                             "1分路带电弧检测",
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION:   "1分路带漏电保护电弧检测",
	DEVICEREGISTER_TYPE_TWOSWITCH:                                              "2分路",
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ELECTRICLEAKAGEPROTECTION:                "2分路带漏电保护",
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ARCDETECTION:                             "2分路带电弧检测",
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION:   "2分路带漏电保护电弧检测",
	DEVICEREGISTER_TYPE_THREESWITCH:                                            "3分路",
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ELECTRICLEAKAGEPROTECTION:              "3分路带漏电保护",
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ARCDETECTION:                           "3分路带电弧检测",
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION: "3分路带漏电保护电弧检测",
	DEVICEREGISTER_TYPE_FOURSWITCH:                                             "4分路",
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ELECTRICLEAKAGEPROTECTION:               "4分路带漏电保护",
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ARCDETECTION:                            "4分路带电弧检测",
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION:  "4分路带漏电保护电弧检测",
}

var DEVICETYPE_REGISTERTYPE = map[uint8]uint8{
	DEVICEREGISTER_TYPE_ONESWITCH:                                              1,
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ELECTRICLEAKAGEPROTECTION:                1,
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ARCDETECTION:                             1,
	DEVICEREGISTER_TYPE_ONESWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION:   1,
	DEVICEREGISTER_TYPE_TWOSWITCH:                                              1,
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ELECTRICLEAKAGEPROTECTION:                1,
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ARCDETECTION:                             1,
	DEVICEREGISTER_TYPE_TWOSWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION:   1,
	DEVICEREGISTER_TYPE_THREESWITCH:                                            2,
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ELECTRICLEAKAGEPROTECTION:              2,
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ARCDETECTION:                           2,
	DEVICEREGISTER_TYPE_THREESWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION: 2,
	DEVICEREGISTER_TYPE_FOURSWITCH:                                             2,
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ELECTRICLEAKAGEPROTECTION:               2,
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ARCDETECTION:                            2,
	DEVICEREGISTER_TYPE_FOURSWITCHWITH_ELECTRICLEAKAGEPROTECTION_ARCDETECTION:  2,
}

var ERRORCODE_MSG = map[uint8]string{
	ERRORCODE_ADDRERROR:     "modbus功能码错误",
	ERRORCODE_REGISTERERROR: "主机/设备地址或寄存器错误",
	ERRORCODE_DEVICEOFFLINE: "请求设备下线",
}

//设备寄存器1map数据
var (
	HARDWAREFAULT_MSG = map[uint8]string{
		DEVICEREGISTER_ONE_HARDWAREFAULT_MEASUREFAULT:    "计量故障",
		DEVICEREGISTER_ONE_HARDWAREFAULT_ELECTRICLEAKAGE: "漏电故障",
		DEVICEREGISTER_ONE_HARDWAREFAULT_TRANSMITTFAULT:  "传动故障",
		DEVICEREGISTER_ONE_HARDWAREFAULT_OPENSTATELIMIT:  "合闸状态限位",
		DEVICEREGISTER_ONE_HARDWAREFAULT_OPENSTOPLIMIT:   "合闸停止限位",
		DEVICEREGISTER_ONE_HARDWAREFAULT_CLOSESTATELIMIT: "分闸状态限位",
		DEVICEREGISTER_ONE_HARDWAREFAULT_CLOSESTOPLIMIT:  "分闸停止限位",
	}
	ALARMSTATE_MSG = map[uint8]string{
		DEVICEREGISTER_ONE_ALARMSTATE_OVERFLOW:         "过流",
		DEVICEREGISTER_ONE_ALARMSTATE_OVERVOLTAGE:      "过压",
		DEVICEREGISTER_ONE_ALARMSTATE_UNDERVOLTAGE:     "欠压",
		DEVICEREGISTER_ONE_ALARMSTATE_OVERDRIVE:        "过载",
		DEVICEREGISTER_ONE_ALARMSTATE_ELECTRICQUANTITY: "电量",
		DEVICEREGISTER_ONE_ALARMSTATE_OVERHEAT:         "过温",
	}
	ALARMENABLE_MSG = map[uint8]string{
		DEVICEREGISTER_ONE_ALARMENABLE_OVERFLOW:         "过流",
		DEVICEREGISTER_ONE_ALARMENABLE_OVERVOLTAGE:      "过压",
		DEVICEREGISTER_ONE_ALARMENABLE_UNDERVOLTAGE:     "欠压",
		DEVICEREGISTER_ONE_ALARMENABLE_OVERDRIVE:        "过载",
		DEVICEREGISTER_ONE_ALARMENABLE_ELECTRICQUANTITY: "电量",
		DEVICEREGISTER_ONE_ALARMENABLE_OVERHEAT:         "过温",
	}
	ERRORSTATE_MSG = map[uint8]string{
		DEVICEREGISTER_ONE_ERRORSTATE_OVERFLOW:         "过流",
		DEVICEREGISTER_ONE_ERRORSTATE_OVERVOLTAGE:      "过压",
		DEVICEREGISTER_ONE_ERRORSTATE_UNDERVOLTAGE:     "欠压",
		DEVICEREGISTER_ONE_ERRORSTATE_OVERDRIVE:        "过载",
		DEVICEREGISTER_ONE_ERRORSTATE_ELECTRICQUANTITY: "电量",
		DEVICEREGISTER_ONE_ERRORSTATE_OVERHEAT:         "过温",
		DEVICEREGISTER_ONE_ERRORSTATE_SHORTOUT:         "短路",
		DEVICEREGISTER_ONE_ERRORSTATE_ELECTRICLEAKAGE:  "漏电",
		DEVICEREGISTER_ONE_ERRORSTATE_GROUNDLEAD:       "地线",
		DEVICEREGISTER_ONE_ERRORSTATE_ELECTRICARC:      "电弧",
	}
	ERRORENABLE_MSG = map[uint8]string{
		DEVICEREGISTER_ONE_ERRORENABLE_OVERFLOW:         "过流",
		DEVICEREGISTER_ONE_ERRORENABLE_OVERVOLTAGE:      "过压",
		DEVICEREGISTER_ONE_ERRORENABLE_UNDERVOLTAGE:     "欠压",
		DEVICEREGISTER_ONE_ERRORENABLE_OVERDRIVE:        "过载",
		DEVICEREGISTER_ONE_ERRORENABLE_ELECTRICQUANTITY: "电量",
		DEVICEREGISTER_ONE_ERRORENABLE_OVERHEAT:         "过温",
		DEVICEREGISTER_ONE_ERRORENABLE_SHORTOUT:         "短路",
		DEVICEREGISTER_ONE_ERRORENABLE_ELECTRICARC:      "电弧",
	}
	SWITCHSTATE_MSG = map[uint16]string{
		DEVICEREGISTER_ONE_SWITCHSTATE_CLOSE:                    "本地关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_OPEN:                     "本地开闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_BUTTONCLOSE:              "按键关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_BUTTONOPEN:               "按键开闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_REMOTECLOSE:              "远程关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_REMOTEOPEN:               "远程开闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_FAULTCLOSE:               "故障关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_AFTERFAULTAUTOOPEN:       "故障自动恢复开闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_TIMEDCLOSE:               "定时关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_TIMEDOPEN:                "定时开闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_SHORTOUTCLOSE:            "短路关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_ELECTRICLEAKAGECLOSE:     "漏电关闸",
		DEVICEREGISTER_ONE_SWITCHSTATE_ELECTRICLEAKAGETESTCLOSE: "漏电测试开闸",
	}
	SWITCHMODE_MSG = map[uint16]string{
		DEVICEREGISTER_ONE_SWITCHMODE_NORMAL:     "正常",
		DEVICEREGISTER_ONE_SWITCHMODE_LOCALLOCK:  "本地锁定",
		DEVICEREGISTER_ONE_SWITCHMODE_REMOTELOCK: "远程锁定",
		DEVICEREGISTER_ONE_SWITCHMODE_FAULTLOCK:  "故障锁定",
		DEVICEREGISTER_ONE_SWITCHMODE_OFFLINE:    "离线",
	}
)
